services:

  core:
    build: ./core
    environment:
      - KNOWLEDGE_CRON=0 5 * * *
      - KNOWLEDGE_DIR=./knowledge
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - LLM_API_KEY=c354fce0-c57f-4f3a-9190-e3598a633d74
    restart: always
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:master
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

volumes:
  qdrant_data:
    driver: local